# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c6816983e91c896754e886d95638f7d230c887c740e173b7266ad3910aa45b5f150d2ad3ddf30a7b1f2c1666f961d6a349b20c74115fb652ebc62e352c029c9

test:
  secret_key_base: 05f7ba498e3442a88ac03cf1f91922fa38510ae1c084638e4c0b86f5f54c15f23cb6a15fb2a2e496bbd36dd51c153db77e4d09f56d20a68ad8c582f1dfad2732

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
